name: Telegram notifications

on: [push, create]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Author name
        id: commit-author
        run: |
          AUTHOR_NAME=$(git log --pretty=format:"%an" -1)
          echo "author-name=${AUTHOR_NAME}" >> $GITHUB_OUTPUT

      - name: Commit comment
        id: text-comment
        run: |
          COMMIT_COMMENT=$(git log --pretty=format:"%s" -1)
          echo "commit-comment=${COMMIT_COMMENT}" >> $GITHUB_OUTPUT

      - name: Generate git diff message
        id: git-diff
        run: |
          DIFF_MESSAGE=$(git diff -w --name-status HEAD~1 HEAD | 
            sed -e 's/^A[^ ]/🆕 Added: /' \
            -e 's/^M[^ ]/✏️ Modified: /' \
            -e 's/^D[^ ]/🗑️ Deleted: /')
          DIFF_MESSAGE_JSON=$(jq -Rs . <<< "$DIFF_MESSAGE")
          echo "diff_message=${DIFF_MESSAGE_JSON}" >> $GITHUB_OUTPUT

      - name: Run on push
        uses: appleboy/telegram-action@master
        if: github.event_name == 'push'
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            New commit delivered
            Author: ${{ steps.commit-author.outputs.author-name }}
            Comment: ${{ steps.text-comment.outputs.commit-comment }}
            Changes:
            ${{ fromJSON(steps.git-diff.outputs.diff_message) }}

      - name: Run on create
        uses: appleboy/telegram-action@master
        if: github.event_name == 'create'
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: 'Create complete'
